/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiTranscribeRouteImport } from './routes/api/ai-transcribe'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as AuthenticatedUsuarioRouteImport } from './routes/_authenticated/usuario'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReferenciasRouteImport } from './routes/_authenticated/referencias'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedOrganizacaoRouteImport } from './routes/_authenticated/organizacao'
import { Route as AuthenticatedOrdensRouteImport } from './routes/_authenticated/ordens'
import { Route as AuthenticatedOrdemCompraRouteImport } from './routes/_authenticated/ordem-compra'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBalancoRouteImport } from './routes/_authenticated/balanco'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranscribeRoute = ApiAiTranscribeRouteImport.update({
  id: '/api/ai-transcribe',
  path: '/api/ai-transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuarioRoute = AuthenticatedUsuarioRouteImport.update({
  id: '/usuario',
  path: '/usuario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferenciasRoute =
  AuthenticatedReferenciasRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizacaoRoute =
  AuthenticatedOrganizacaoRouteImport.update({
    id: '/organizacao',
    path: '/organizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensRoute = AuthenticatedOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdemCompraRoute =
  AuthenticatedOrdemCompraRouteImport.update({
    id: '/ordem-compra',
    path: '/ordem-compra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalancoRoute = AuthenticatedBalancoRouteImport.update({
  id: '/balanco',
  path: '/balanco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/landing': typeof LandingRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/balanco': typeof AuthenticatedBalancoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ordem-compra': typeof AuthenticatedOrdemCompraRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/referencias': typeof AuthenticatedReferenciasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuario': typeof AuthenticatedUsuarioRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-transcribe': typeof ApiAiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/landing': typeof LandingRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/balanco': typeof AuthenticatedBalancoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ordem-compra': typeof AuthenticatedOrdemCompraRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/referencias': typeof AuthenticatedReferenciasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuario': typeof AuthenticatedUsuarioRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-transcribe': typeof ApiAiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/landing': typeof LandingRoute
  '/super-admin': typeof SuperAdminRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/balanco': typeof AuthenticatedBalancoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/ordem-compra': typeof AuthenticatedOrdemCompraRoute
  '/_authenticated/ordens': typeof AuthenticatedOrdensRoute
  '/_authenticated/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/referencias': typeof AuthenticatedReferenciasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuario': typeof AuthenticatedUsuarioRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-transcribe': typeof ApiAiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/landing'
    | '/super-admin'
    | '/admin'
    | '/balanco'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/ordem-compra'
    | '/ordens'
    | '/organizacao'
    | '/produtos'
    | '/referencias'
    | '/relatorios'
    | '/usuario'
    | '/api/ai-chat'
    | '/api/ai-transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/landing'
    | '/super-admin'
    | '/admin'
    | '/balanco'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/ordem-compra'
    | '/ordens'
    | '/organizacao'
    | '/produtos'
    | '/referencias'
    | '/relatorios'
    | '/usuario'
    | '/api/ai-chat'
    | '/api/ai-transcribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/landing'
    | '/super-admin'
    | '/_authenticated/admin'
    | '/_authenticated/balanco'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/ordem-compra'
    | '/_authenticated/ordens'
    | '/_authenticated/organizacao'
    | '/_authenticated/produtos'
    | '/_authenticated/referencias'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuario'
    | '/api/ai-chat'
    | '/api/ai-transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  LandingRoute: typeof LandingRoute
  SuperAdminRoute: typeof SuperAdminRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiTranscribeRoute: typeof ApiAiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-transcribe': {
      id: '/api/ai-transcribe'
      path: '/api/ai-transcribe'
      fullPath: '/api/ai-transcribe'
      preLoaderRoute: typeof ApiAiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuario': {
      id: '/_authenticated/usuario'
      path: '/usuario'
      fullPath: '/usuario'
      preLoaderRoute: typeof AuthenticatedUsuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referencias': {
      id: '/_authenticated/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof AuthenticatedReferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizacao': {
      id: '/_authenticated/organizacao'
      path: '/organizacao'
      fullPath: '/organizacao'
      preLoaderRoute: typeof AuthenticatedOrganizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens': {
      id: '/_authenticated/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AuthenticatedOrdensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordem-compra': {
      id: '/_authenticated/ordem-compra'
      path: '/ordem-compra'
      fullPath: '/ordem-compra'
      preLoaderRoute: typeof AuthenticatedOrdemCompraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balanco': {
      id: '/_authenticated/balanco'
      path: '/balanco'
      fullPath: '/balanco'
      preLoaderRoute: typeof AuthenticatedBalancoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBalancoRoute: typeof AuthenticatedBalancoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOrdemCompraRoute: typeof AuthenticatedOrdemCompraRoute
  AuthenticatedOrdensRoute: typeof AuthenticatedOrdensRoute
  AuthenticatedOrganizacaoRoute: typeof AuthenticatedOrganizacaoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedReferenciasRoute: typeof AuthenticatedReferenciasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuarioRoute: typeof AuthenticatedUsuarioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBalancoRoute: AuthenticatedBalancoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOrdemCompraRoute: AuthenticatedOrdemCompraRoute,
  AuthenticatedOrdensRoute: AuthenticatedOrdensRoute,
  AuthenticatedOrganizacaoRoute: AuthenticatedOrganizacaoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedReferenciasRoute: AuthenticatedReferenciasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuarioRoute: AuthenticatedUsuarioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  LandingRoute: LandingRoute,
  SuperAdminRoute: SuperAdminRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiTranscribeRoute: ApiAiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
