ALTER TABLE public.service_orders
  ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS scheduled_has_time BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS service_address TEXT,
  ADD COLUMN IF NOT EXISTS service_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS service_lng DOUBLE PRECISION;